basic:
    name: Aletria
    environments:
        production: 'https://aletria.pt/'
        staging: '[https://www.figma.com/design/sTro9Iinjez4hEHCqDrI96/ALETRIA---Biblioteca-Itinerante?node-id=1311-2805\&t=9UOlWvHpA04jY2Cv-1](https://www.figma.com/design/sTro9Iinjez4hEHCqDrI96/ALETRIA---Biblioteca-Itinerante?node-id=1311-2805&t=9UOlWvHpA04jY2Cv-1)'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
